spring:
  datasource:
    url: jdbc:mysql:///bjznk?useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    hikari:
      pool-name: ==DateHikariCP==
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 60
      connection-test-query: SELECT 1
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 50000
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: DEBUG
    org:
      hibernate: DEBUG
    cn:
      bjznk: DEBUG